### ISSUE TITLE
ms revision to-do

### ISSUE THREAD

**Issue by ajrominger** [ecoevomatics/EcoEvoNonStat#2]
- [ ] figure out what to do with boxes/glossary
- [ ] bring in new lit, e.g. MESS paper, Frontiers in Eco Evo special issue, MEC special issue on metabarcoding, McGill macro-macro paper
- [ ] clean up parenthetical citations like rmd: `(e.g., @stuff)`, `this is found by @people`
- [ ] move discussion of neutrality and stat mech to earlier in intro
- [ ] decide on wording around 'equilibrium' and 'stationary'
- [ ] decide on ms format: opinion or methods?
